import type { Metadata } from "next";
import NavBar from "@/components/NavBar/NavBar";
import Footers from "@/components/Footers/Footers";
import DeliveryDetails from "@/components/Body/SectoinEnd/DeliveryDetails/DeliveryDetails";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen">
          <NavBar />
          {children}
          <DeliveryDetails />
        </div>
        <Footers />
      </body>
    </html>
  );
}
